name: Build Installers

on:
  push:
    tags:
      - 'v*'          # tag to trigger a release build, e.g. v1.0.0
  workflow_dispatch:   # allow manual runs

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Build installers (Windows)
        run: ./gradlew --no-daemon clean jpackage shadowJar
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            build/jpackage/**/*
            build/libs/*.jar

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Build installers (macOS)
        run: ./gradlew --no-daemon clean jpackage shadowJar
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            build/jpackage/**/*
            build/libs/*.jar

  release:
    needs: [windows, macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: dist/windows
      - uses: actions/download-artifact@v4
        with:
          name: macos-artifacts
          path: dist/macos
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/windows/build/jpackage/**
            dist/macos/build/jpackage/**
            dist/windows/build/libs/*.jar
            dist/macos/build/libs/*.jar
